### ISSUE TITLE
Query about the utility of this project from a contributor's perspective

### ISSUE THREAD

**Issue by abhisheks008** [utkarsh006/LeetCode-Grind#23]
Hey, LeetCode-Grind team, got to know about your project from HSOC 2022 website. This project repo is all about storing the solutions of the daily challenge of LeetCode. If I want to contribute in this repository as a contributor then how should I be able to contribute here, as @utkarsh006 and @gurjeetsinghvirdee are adding the proper solutions everyday. Also there are no pull requests in this repo, everyone is creating issues for editing the README.md file, nothing else! I just wanted to know how this is going to be beneficial for the contributors, and also what's the purpose of this project. Can you please elaborate it?

Thanks and regards 🚀

**Comment by gurjeetsinghvirdee** [comment]
@utkarsh006 is the PA of this project even though I contributed to this repository the first time not every day!
Maybe you can add more solutions to the monthly challenges.

**Comment by utkarsh006** [comment]
Hey Abhishek I hope you're doing extremely well. I hope you may have found another repo named "TIC TAC TOE" in which there are no active PR'S and it is beneficial for Kotlin contributors. Also, it is not for beginners and I am PA for that. Let's come to your question :)

1. Creating and Finding issues depends upon the contributors and if you closely observe there are many issues left that can help newbies to start their journey in open source. It is a beginner-friendly project. It also has issues and 6 PR'S Merged till now.

2. Many questions are left to add in a repo, Currently, there is no January Folder. 

3. Also, I am accepting one question and one issue at a time from one contributor.

4. See the list of all merged PR'S till now which would help in clarifying all your doubts.

5. I hope you are into Coding. If you aren't much into that part; let me tell you that 95% of the companies ask leetcode questions in their Interviews. As a beginner, if a student has no idea about interviews then he/she could simply refer to this repo for revision of DSA.

6. 1 Year = 365 problems and each problem of Leetcode is enough for brushing up on your concepts. Also, in each folder there are questions that are marked as Important.

I hope I have cleared all your doubts✔

NOTE : We and @gurjeetsinghvirdee didn't create hype for our project which can be the reason that people didn't get what value it provides. The project will help students in brushing up their DSA skills Also, instead of spreading such comments and making themselves more accountable, people should research well before making such comments and contact PA over the discord as per the rules of this open source program HackClub RAIT. 
No hate, we only support folks in Open source and spread love to the Community 🙏🏼
NO HYPE, NO GIFTS, ONLY LEARNING !!!
Signing off .....
Utkarsh Saxena
